version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/pkg/plugin/sdk"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tool/actions-gh-release"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tool/actions-plan-preview"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/tool/codegen/protoc-gen-auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/app/pipedv1/plugin/kubernetes"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/app/pipedv1/plugin/kubernetes_multicluster"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/app/pipedv1/plugin/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/pkg/app/pipedv1/plugin/cloudrun"
    schedule:
      interval: "weekly"
