apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: secret-management
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '2'
    spec:
      containerConcurrency: 80
      containers:
      - args:
          - server
        image: gcr.io/pipecd/piped:v0.27.4
        env:
          - name: KEY
            value: "{{ .encryptedSecrets.key }}"
        ports:
          - containerPort: 9085
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
