# Gateway workload by using Envoy proxy.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-gateway
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  replicas: {{ .Values.gateway.replicasCount }}
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gateway
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: envoy
          image: envoyproxy/envoy-alpine:{{ .Values.gateway.imageTag }}
          imagePullPolicy: IfNotPresent
          command:
          - envoy
          args:
            - -c
            - /etc/envoy/envoy-config.yaml
          ports:
          - name: ingress
            containerPort: 9090
            protocol: TCP
          - name: envoy-admin
            containerPort: 9095
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /server_info
              port: envoy-admin
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /server_info
              port: envoy-admin
          volumeMounts:
          - name: envoy-config
            mountPath: /etc/envoy
            readOnly: true
          - name: pipecd-secret
            mountPath: {{ .Values.secret.mountPath }}
            readOnly: true
{{- if .Values.gateway.resources }}
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
{{- end }}
      volumes:
        - name: envoy-config
          configMap:
            name: {{ include "pipecd.fullname" . }}-gateway-envoy-config
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}

---
# API workload.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-server
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicasCount }}
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.quickstart.enabled }}
      initContainers:
        - name: dep-waiter
          image: alpine:3.14
          command: ["sh", "-c"]
          args:
            - |
              until nc -z {{ include "pipecd.fullname" . }}-minio {{ .Values.minio.port }} && nc -z {{ include "pipecd.fullname" . }}-mysql {{ .Values.mysql.port }}
              do
                sleep 2;
              done;
      {{- end }}
      containers:
{{- if .Values.cloudSQLProxy.enabled }}
        - name: cloud-sql-proxy
          image: "gcr.io/cloudsql-docker/gce-proxy:{{ .Values.cloudSQLProxy.version }}"
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.cloudSQLProxy.args.instanceConnectionName }}=tcp:{{ .Values.cloudSQLProxy.args.port }}"
            - "-credential_file={{ .Values.secret.mountPath }}/{{ .Values.secret.cloudSQLServiceAccount.fileName }}"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
{{- if .Values.cloudSQLProxy.resources }}
          resources:
            {{- toYaml .Values.cloudSQLProxy.resources | nindent 12 }}
{{- end }}
{{- end }}
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - server
{{- if not .Values.server.args.secureCookie }}
          - --insecure-cookie=true
{{- end }}
          - --cache-address={{ .Values.server.args.cacheAddress | default (printf "%s-cache:6379" (include "pipecd.fullname" .)) }}
          - --config-file=/etc/pipecd-config/{{ .Values.config.fileName }}
          - --enable-grpc-reflection={{ .Values.server.args.enableGRPCReflection }}
          - --encryption-key-file={{ .Values.secret.mountPath }}/{{ .Values.secret.encryptionKey.fileName }}
          - --log-encoding={{ .Values.server.args.logEncoding }}
          - --log-level={{ .Values.server.args.logLevel }}
          - --metrics={{ .Values.server.args.metrics }}
          ports:
            - name: piped-api
              containerPort: 9080
              protocol: TCP
            - name: web-api
              containerPort: 9081
              protocol: TCP
            - name: http
              containerPort: 9082
              protocol: TCP
            - name: api
              containerPort: 9083
              protocol: TCP
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            - name: pipecd-config
              mountPath: /etc/pipecd-config
              readOnly: true
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 30" ]
{{- if .Values.server.resources }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
{{- end }}
{{- if .Values.server.env }}
          env:
            {{- toYaml .Values.server.env | nindent 12 }}
{{- end }}

      volumes:
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}
        - name: pipecd-config
          configMap:
            name: {{ include "pipecd.configMapName" . }}

---
# Cache workload.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-cache
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cache
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: cache
          image: redis:{{ .Values.cache.imageTag }}
          imagePullPolicy: IfNotPresent
  {{- if .Values.cache.password }}
          args:
            - --requirepass
            - {{ .Values.cache.password | quote }}
  {{- end }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
{{- if .Values.cache.resources }}
          resources:
            {{- toYaml .Values.cache.resources | nindent 12 }}
{{- end }}

---
# Single ops pod.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-ops
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: ops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ops
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ops
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.quickstart.enabled }}
      initContainers:
        - name: dep-waiter
          image: alpine:3.14
          command: ["sh", "-c"]
          args:
            - |
              until nc -z {{ include "pipecd.fullname" . }}-minio {{ .Values.minio.port }} && nc -z {{ include "pipecd.fullname" . }}-mysql {{ .Values.mysql.port }}
              do
                sleep 2;
              done;
      {{- end }}
      containers:
{{- if .Values.cloudSQLProxy.enabled }}
        - name: cloud-sql-proxy
          image: "gcr.io/cloudsql-docker/gce-proxy:{{ .Values.cloudSQLProxy.version }}"
          command:
            - "/cloud_sql_proxy"
            - "-instances={{ .Values.cloudSQLProxy.args.instanceConnectionName }}=tcp:{{ .Values.cloudSQLProxy.args.port }}"
            - "-credential_file={{ .Values.secret.mountPath }}/{{ .Values.secret.cloudSQLServiceAccount.fileName }}"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
{{- end }}
        - name: ops
          image: "{{ .Values.ops.image.repository }}:{{ .Values.ops.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
          - ops
          - --cache-address={{ .Values.ops.args.cacheAddress | default (printf "%s-cache:6379" (include "pipecd.fullname" .)) }}
          - --config-file=/etc/pipecd-config/{{ .Values.config.fileName }}
          - --log-encoding={{ .Values.ops.args.logEncoding }}
          - --log-level={{ .Values.ops.args.logLevel }}
          - --metrics={{ .Values.ops.args.metrics }}
          ports:
            - name: http
              containerPort: 9082
              protocol: TCP
            - name: admin
              containerPort: 9085
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: admin
          readinessProbe:
            httpGet:
              path: /healthz
              port: admin
          volumeMounts:
            - name: pipecd-secret
              mountPath: {{ .Values.secret.mountPath }}
              readOnly: true
            - name: pipecd-config
              mountPath: /etc/pipecd-config
              readOnly: true
{{- if .Values.ops.resources }}
          resources:
            {{- toYaml .Values.ops.resources | nindent 12 }}
{{- end }}
      volumes:
        - name: pipecd-secret
          secret:
            secretName: {{ include "pipecd.secretName" . }}
        - name: pipecd-config
          configMap:
            name: {{ include "pipecd.configMapName" . }}

{{- if .Values.quickstart.enabled }}
---
# MySQL datastore
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-mysql
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mysql
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}:{{ .Values.mysql.imageTag }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.port }}
              protocol: TCP
{{- if .Values.mysql.resources }}
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
{{- end }}

---
# MinIO File Store
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pipecd.fullname" . }}-minio
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pipecd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: minio
  template:
    metadata:
      labels:
        {{- include "pipecd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: minio
    spec:
      {{- if or .Values.serviceAccount.create .Values.serviceAccount.name }}
      serviceAccountName: {{ include "pipecd.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: minio
          image: minio/minio:{{ .Values.minio.imageTag }}
          args:
          - server
          - /data
          env:
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "pipecd.secretName" . }}
                key: {{ .Values.secret.minioAccessKey.fileName }}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "pipecd.secretName" . }}
                key: {{ .Values.secret.minioSecretKey.fileName }}
          ports:
            - name: minio
              containerPort: {{ .Values.minio.port }}
              protocol: TCP
{{- if .Values.minio.resources }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
{{- end }}
{{- end }}
