{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "pipecd.fullname" . }}
  labels:
    {{- include "pipecd.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.managedCertificate.enabled }}
    networking.gke.io/managed-certificates: {{ include "pipecd.fullname" . }}
  {{- end }}
spec:
  {{- if .Values.service.internalPort }}
  backend:
    serviceName: {{ include "pipecd.fullname" . }}
    servicePort: {{ .Values.service.internalPort }}
  rules:
  - http:
      paths:
      - path: /hook
        backend:
          serviceName: {{ include "pipecd.fullname" . }}
          servicePort: {{ .Values.service.port }}
      - path: /pipe.api.service.pipedservice.PipedService/*
        backend:
          serviceName: {{ include "pipecd.fullname" . }}
          servicePort: {{ .Values.service.port }}
      - path: /pipe.api.service.apiservice.APIService/*
        backend:
          serviceName: {{ include "pipecd.fullname" . }}
          servicePort: {{ .Values.service.port }}
  {{ else }}
  backend:
    serviceName: {{ include "pipecd.fullname" . }}
    servicePort: {{ .Values.service.port }}
  {{- end }}
{{- end }}
