apiVersion: apps/v1
kind: Deployment
metadata:
  name: analysis-by-log
  labels:
    app: analysis-by-log
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analysis-by-log
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: analysis-by-log
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: ghcr.io/pipe-cd/helloworld:v0.30.0
        args:
          - server
        ports:
        - containerPort: 9085
