apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  name: kustomize-local-base
  labels:
    env: example
    team: product
  trigger:
    onCommit:
      paths:
        - local-modules/kustomize-bases/helloworld/*
  input:
    kustomizeVersion: 3.5.5
  description: |
    This app demonstrates how to deploy a Kubernetes app that uses a Kustomize package sourced from the same Git repository.\
    References: [adding a new app](https://pipecd.dev/docs/user-guide/adding-an-application/), [app configuration](https://pipecd.dev/docs/user-guide/configuration-reference/)
