apiVersion: apps/v1
kind: Deployment
metadata:
  name: mesh-istio-bluegreen
  labels:
    app: mesh-istio-bluegreen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mesh-istio-bluegreen
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: mesh-istio-bluegreen
        pipecd.dev/variant: primary
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: helloworld
        image: gcr.io/pipecd/helloworld:v0.6.0
        args:
          - server
        ports:
        - containerPort: 9085
