name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  cla:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == '/cla sign') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@b3bbab0a75fa27270069933cec6f369c0b373b4e #v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          remote-organization-name: pipe-cd
          remote-repository-name: pipecd-cla
          path-to-signatures: 'cla/signatures.json'
          path-to-document: 'https://github.com/pipe-cd/pipecd/blob/master/CLA.md'
          custom-notsigned-prcomment: "Welcome $contributorName!\nThanks for your contributing. It looks like this is your first PR to this repository ðŸŽ‰. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). Please read the [CLA](https://github.com/pipe-cd/pipecd/blob/master/CLA.md) and leave a `/cla sign` comment on this pull request to sign the CLA."
          custom-pr-sign-comment: '/cla sign'
          custom-allsigned-prcomment: 'All Contributors have signed the CLA.'
          lock-pullrequest-aftermerge: false
          branch: 'main'
