name: Dockers Test

on:
  push:
    branches:
      - master
    paths:
      - dockers/**
  pull_request:
    branches:
      - master
    paths:
      - dockers/**

jobs:
  backend:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - name: Run unit tests for actions-plan-preview
        working-directory: dockers/actions-plan-preview
        run: go test ./...

      - name: Run unit tests for actions-gh-release
        working-directory: dockers/actions-gh-release
        run: go test ./...
